### ISSUE TITLE
feat: banner to warn users when they look at documentation for an outdated platform version

### ISSUE THREAD

**Issue by fhennig** [stackabletech/documentation-ui#36]
To prevent users from accidentally looking at documentation that might be outdated, we should add a banner or info box somewhere on the page that indicates that the version is not the latest.

This might also help with SEO, as every old page will link to the new page, giving the new/stable pages more weight.

Others do it as well:

- [rust: kube-rs](https://docs.rs/kube/0.76.0/kube/index.html)
- [kubernetes](https://v1-24.docs.kubernetes.io/)
- [django docs](https://docs.djangoproject.com/en/3.1/intro/tutorial01/)
```[tasklist]
### Tasks
- [x] create a nice HTML&CSS style for such a banner
- [x] find a way to link to the stable version of the same page if there is one (maybe simply the 'canonical' version?)
- [x] find a way to display this banner on outdated versions (needs to be done with handlebars helpers probably)
- [ ] https://github.com/stackabletech/documentation-ui/pull/57
- [ ] https://github.com/stackabletech/documentation/pull/584
- [x] Tag all release branches with eol true/false
```

## Which versions are outdated?

We should display such a banner on versions that are 'end of life' which are all versions that are more than 12 months old.

It would be good to manually set an `eol` flag in the `antora.yml` in each branch and display the banner based on that.

For example like this:

```yaml
asciidoc:
  attributes:
    # Whether this version is already end of life. 
    # If true, a banner will be displayed informing the user.
    end-of-life: true
    # to make attributes accessible to the UI template, they need to
    # be prefixed with "page-"
    page-end-of-life: "{end-of-life}"
```

## Acceptance criteria

- Every page for a platform version that is older than stable displays a warning banner that links to the latest version of the page
- stretch goal: there is a similar banner for nightly docs
- every branch from 23.1 is marked as either end-of-life or not

**Comment by fhennig** [comment]
Open questions:
- ~~How to style it~~
- Should there be an 'x' to click it away? :x: 
- Should it scroll out of view (probably it should) :heavy_check_mark:
